### ISSUE TITLE
Move to Cake-Contrib Organisation

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.ArgumentHelpers#7]
@patridge  I was just doing an audit of some of the Cake addins which haven't been updated in a while, and I noticed that this was one of them.

Would you be interested in moving this addin into the Cake-Contrib GitHub Organisation, so that other folks can help with getting it updated?

Thanks

**Comment by patridge** [comment]
@gep13 Despite a good few years of using Cake for everything I could, I haven't been using Cake for the last 3 years. I somehow missed any notifications from GitHub with the usual onslaught of emails. Since I'm not in a place to even test this code base anymore, let's make it happen. The NuGet is already co-owned, so at least that's set. I'll see if I can start the process.

**Comment by patridge** [comment]
<[Some context is happening on Twitter, too](https://twitter.com/gep13/status/1273352209439305728)>

**Comment by gep13** [comment]
@patridge thanks for doing this!
